credentials:
  account_0:
    username: "dogmoore"
    password: "testing"
    raw_password: "dGVzdGluZw=="
    security:
      enabled: False
      type: 1
      encoding: "utf-8"
  account_1:
    username: "test"
    password: "1234"
    security:
      enabled: False
      type: 0
      encoding: "utf-8"
  account_2:
    username: "qwerty"
    password: "1234"
    security:
      enabled: False
      type: 0
      encoding: "utf-8"
  account_3:
    username: "xx"
    password: "test"
    security:
      enabled: False
      type: 0
      encoding: "utf-8"
  account_4:
    username: "mandy"
    password: "1234"
    security:
      enabled: False
      type: 0
      encoding: "utf-8"
  account_5:
    username: "dave"
    password: "1234"
    security:
      enabled: False
      type: 0
      encoding: "utf-8"
  account_6:
    username: 'admin'
    password: 'debug only'
    security:
      enabled: False
      type: 0
      encoding: "utf-8"