Leather Armor: {
  Leather Armor: {
    Armor Class: 11,
    Weight: 10,
    cost: 10,
    Description: 'The breastplate and shoulder protectors of this armor are made of leather that has been stiffened by being boiled in oil. The rest of the armor is made of softer and more flexible materials.'
  }
}
Sickle: {
  Sickle: {
    Attack Type: 'Melee',
    Damage Type: 'Slashing',
    Reach: 5,
    Damage: '1d4',
    Weight: '2',
    Cost: '1',
    Description: 'Proficiency with a Sickle allows you to add your proficiency bonus to the attack roll for any attack you make with it.',
    Properties: {
      Light: True,
      Nick: True
    }
  }
}
Dagger: {
  Dagger: {
    Attack Type: 'Melee',
    Damage Type: 'Piercing',
    Reach: 5,
    Range_min: 20,
    Range_max: 60,
    Damage: '1d4',
    Weight: 1,
    Cost: 2,
    Description: 'Proficiency with a Dagger allows you to add your proficiency bonus to the attack roll for any attack you make with it.',
    Properties: {
      Finesse: True,
      Light: True,
      Thrown: True,
      Nick: True
    }
  }
}